//=== DANG NHAP
export const YEU_CAU_DANG_NHAP = "YEU_CAU_DANG_NHAP";
export const DANG_NHAP_THANH_CONG = "DANG_NHAP_THANH_CONG";
export const FIRST_LOGIN_THANH_CONG = "FIRST_LOGIN_THANH_CONG";
export const DANG_NHAP_THAT_BAI = "DANG_NHAP_THAT_BAI";
export const DANG_XUAT ="DANG_XUAT";

//=== Cap nhat nhan vien
export const YEU_CAU_CAP_NHAT_USER = "YEU_CAU_CAP_NHAT_USER";
export const CAP_NHAT_USER_THANH_CONG = "CAP_NHAT_USER_THANH_CONG";
export const CAP_NHAT_USER_THAT_BAI = "CAP_NHAT_USER_THAT_BAI";

